runtime: php74

env_variables:
    CLOUDSQL_CONNECTION_NAME: "/cloudsql/php-projects-333723:southamerica-west1:tasks-db"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "emA6b4j01LspPwkL"
    CLOUDSQL_DATABASE_NAME: "tasks"